[package]
name = "Assignment_two"
version = "0.1.0"
authors = ["UmerMIB <47888725+UmerMIB@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
quickersort = "3.0.1"
text_io = "0.1.7"
